pytorch/torchchat

- README.md
Specify the steps to create `android/Torchchat/app/libs/`, and to rename the AAR file.
> Update Android instrucitons on README.md

- generate.py
FIx the first token time metric by yielding metrics as they're generated and handling it via a dict.update().
Test:
```
python3 torchchat.py generate stories15M --prompt "Once upon a time," --max-new-tokens 256 --compile
Warning: compilation is not available with device MPS, ignoring option to engage compilation
NumExpr defaulting to 10 threads.
PyTorch version 2.5.0.dev20240710 available.
Using device=mps 
Time to load model: 0.37 seconds
Once upon a time, there was a little boy named Timmy. Timmy lived in a small house with his family. One day, Timmy's mom asked him to help her with the groceries. Timmy was happy to help, but he was worried about his toy box.
As Timmy walked to the groceries, he saw a man with …
```
> Fix First Token Time metric in generate

- README.md
RERADME: https://github.com/pytorch/torchchat/tree/Jack-Khuu-patch-10
> Organize the Android instruction in the README into steps

- api/api.py
Completion was accessing a None (from chunk with first token time), this adds a check beforehand. 
Create SErver:
`python3 torchchat.py server llama3 --device mps`
```
jackkhuu@jackkhuu-mbp oss % curl http://127.0.0.1:5000/chat \
-d '{
"model": "llama3",
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"content": "Hello!"
}
]
}'
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
jackkhuu@jackkhuu-mbp oss % curl http://127.0.0.1:5000/chat \
-d '{
"model": …
```
> Bugfix: OpenAiApiGenerator.completion() crashes due to None token

- README.md
README: https://github.com/pytorch/torchchat/tree/Jack-Khuu-patch-11
> README.md: Add 3.1 to the table

- cli.py
num-samples is currently associated and listed for all inference generation related commands, but is only utilized in **generate**
Explicitly restrict the arg
Chat
```
python torchchat.py chat --help
usage: torchchat chat [-h] [--checkpoint-path CHECKPOINT_PATH] [--dso-path DSO_PATH | --pte-path PTE_PATH] [--compile] [--compile-prefill]
[--dtype {fp32,fp16,bf16,float,half,float32,float16,bfloat16,fast,fast16}] [--quantize QUANTIZE] [--device {fast,cpu,cuda,mps}] [--max-new-tokens MAX_NEW_TOKENS]
[--top-k TOP_K] [--temperature TEMPERATURE] [--hf-token HF_TOKEN] [--model-directory MODEL_DIRECTORY] [-v] [--seed SEED]
[model]
options:
-h, --help            show this help message and exit
-v, --verbose         Verbose output
--seed SEED           Initialize torch seed
Model Specification: …
```
> [Easy] Update --help so that Generate is the only command that has num_samples

- README.md
README: https://github.com/pytorch/torchchat/tree/Jack-Khuu-patch-13
> README: Remove Llama2 aar + Center images

- docs/README.md
- docs/model_customization.md
- docs/quantization.md
Dedup and refactor of quantization.md
README: https://github.com/pytorch/torchchat/blob/Jack-Khuu-patch-15/docs/quantization.md
> Docs: Deduplicate quantization.md with the introduction of model_customization.md

- distributed/README.md
Marking the directory as experimental until we are ready
> README: Add README to distributed

- distributed/README.md
This PR:
clarifies that distributed dir is to enable future support for large scale multi-node inference.
> update distributed readme

- README.md
This AAR is helpful for testing older/smaller models
https://github.com/pytorch/torchchat/issues/977
> README: Add AAR for sentencepiece

- api/models.py
Incorrect parameter name as mentioned in https://github.com/pytorch/torchchat/issues/1019
> Change owner -> owned_by in models endpoint response

- browser/browser.py
- generate.py
Modified encode_message and encode_dialog_prompt methods in generate.py to resolve streamlit errors.
> Make API and server compatible with OpenAI API

- build/model_dist.py
- dist_run.py
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #1060
* __->__ #1059
Use `parallelize_module` in model.
Added files:
`model_dist.py`: a mirror of model.py with Tensor Parallelism baked in.
`dist_run.py`: toy example of how to run the model in distributed way.
Test:
`torchrun --nproc-per-node 2 dist_run.py`
> Initial add of distributed model

- dist_run.py
- install/.lintrunner.toml
- torchchat/cli/builder.py
- torchchat/cli/cli.py
- torchchat/export.py
- torchchat/generate.py
- torchchat/model_config/model_config.py
- torchchat/model_dist.py
- torchchat/usages/eval.py
- torchchat/usages/openai_api.py
- torchchat/usages/server.py
- torchchat/utils/gguf_loader.py
- torchchat/utils/quantize.py
Linting only subsections of the files that were impacted by the refactor. Specifically, most of the lints revolve around the import lines
* Intentionally not including the lint of the entire file to avoid confounding changes
> [Hackability Refactor] Restricted Lint

- README.md
> [easy] README: typo- missing where

- dist_run.py
This PR:
1 - integrates the chat Tokenizers by using the TokenizerArgs and _inititialize_tokenizer functions from builder.py. 
With the _build_chat_tokenizer() you can instantiate the same tokenizers as installed by chat (rather than using HF tokenizer). 
example:
~~~
[rank0]:2024-09-05:15:57:26,835 INFO     [dist_run.py:83] using tokenizer = tokenizer.tiktoken.Tokenizer
~~~
and
~~~
[rank0]:2024-09-05:16:01:01,716 INFO     [dist_run.py:83] using tokenizer = sentencepiece.SentencePieceProcessor
~~~
2 - adds llama3-8B instructional as a valid model for dist.
> [distributed] integrate chat tokenizers, and add llama3-8B model option

- torchchat/generate.py
This PR is to add max-autotune option for prefill, and remove autotuning log config. Users can autotuning log config by themselves.
> Add max-autotune option for prefill

- torchchat/generate.py
As titled, no functional logic difference, just making the printouts prettier
```
Hello my name is Emily and welcome to my travel blog.
I am a travel blogger and writer from the United States, born and raised in Southern California, but currently residing in New York City. From a young age, I have always had a passion for exploring new
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                
Generated 49 tokens                 
Time for inference 1: 5.0354 sec total                 
Time to first token: 2.0772 sec with parallel prefill.                
Total throughput: 9.9296 tokens/sec, 0.1007 s/token                 
First token throughput: 0.4814 tokens/sec, 2.0772 s/token                 
Next token throughput: 16.5637 tokens/sec, 0.0604 s/token                     
Bandwidth …
```
> [Easy] Improve Print Formatting for generate stats

- torchchat/export.py
> [easy] Removing unused imports/args in export.py

- install/install_requirements.sh
This PR tries to add torchtune support on linux, to have a unify specific version for us to test torchtune with torchchat on linux machine.
> Install torchtune on linux

- torchchat/utils/scripts/install_utils.sh
Check if ExecuTorch is already cloned and no local changes. If
so, skip cloning.
Test Plan: Manually run `install_et.sh` several times and made sure it's
not cloning.
> Improve clone et

- torchchat/generate.py
check for cuda before outputting max memory.
> memory profiling is only available for cuda

- install/install_requirements.sh
- torchchat/generate.py
```
python3 torchchat.py generate --prompt "What's in this image?" --image-prompt dog.jpg --checkpoint-path consolidated.pth --params-path flamingo.json --tokenizer-path tokenizer.model --device cuda --temperature 0
```
> Bump nightly torchtune pin to 2024-09-16

- install/install_requirements.sh
As title
Picking up https://github.com/pytorch/torchtune/commit/3fddc56942846220b39945559f4b5e695873bb43
```
python torchchat.py generate llama3.2-11B --prompt "What's in this image?" --image-prompt assets/dog.jpg
```
Preliminary test gets me around 2.5-3 tps on M1 Max 64GB
> Adding MPS Support for LLama3.2 11B Multimodal; Bump torchtune 9.28.24

- docs/multimodal.md
https://github.com/pytorch/torchchat/blob/47b77b3d5d38bcb1044878d77e8bd5847e199abf/docs/multimodal.md
> Update multimodal.md to show server example

- index.html
A temporary redirect from the site to the repo.
> Add a redirect from pytorch/torchchat to the github repo

- README.md
rename name of. slack channel for our valuable contributors from torchchat-contribution to torchchat-contributors
> Update contributor channel name

- .ci/scripts/run-docs
- .github/workflows/run-readme-pr.yml
- docs/multimodal.md
1 - Complete markup for testing
2 - add test extraction from multimodal.md to run-docs
3 - run generated test from git workflows 
Notes:
a - need to use actual llama model because stories models do not support multimodal inputs
b - this will require HF access tokens which are currently not necessary because stories models can be downloaded without tokens
c - use of HF access tokens are currently not used (?), so might require additional setup
> Add multimodal to possible tests

- torchchat/cli/builder.py
> Fix English language usage in Runtime exception for builder.py

- docs/quantization.md
https://github.com/pytorch/torchchat/issues/1385
> Update quantization.md link to quantize.py

- .github/workflows/pull.yml
- .gitmodules
- CMakeLists.txt
- runner/run.cpp
- tokenizer/CMakeLists.txt
- tokenizer/base.py
- tokenizer/base64.h
- tokenizer/hf_tokenizer.py
- tokenizer/sentencepiece.cpp
- tokenizer/tiktoken.cpp
- tokenizer/tiktoken.py
- tokenizer/tokenizer.h
- torchchat/utils/scripts/build_native.sh
This reverts commit fff956c5c3a68025025c5d906af80eb44e960ce4.
Tokenizer for 3.2-1b got bugged up in the migration, backing out
Flagged in https://github.com/pytorch/torchchat/issues/1413
> Revert "Use pytorch-labs/tokenizers and remove tokenizer/ (#1401)"

- README.md
Consistent spacing around punctuation
> Formatting in README.md

- torchchat/utils/quantize.py
> Fix language in quantize.py

- torchchat/cli/cli.py
Fix missing format string specifier
> Info Message fix in cli.py

- install/install_requirements.sh
Bumping pin to https://github.com/pytorch/ao/commit/7d8794622f3ac7ffa98761314019a20fba06edef
> Bump torchao pin closer to nightly: 2/26/2025

- README.md
Consolidating communication channels into Discord (PyTorch Edge): https://discord.gg/hm2Keduk3v
> Direct Community to Discord instead of Slack

- install/install_torch.sh
Testing pin bump prior to updating install instructions for torch
> Bump PT pins to April 17th
