build/known_model_params/Meta-Llama-3.1-70B.json
build/known_model_params/Meta-Llama-3.1-8B.json
build/model.py
config/data/models.json

Llama3.1 8b now is supported in torchchat! 🎉
Local test:

Support llama3.1-8b generation

---

scripts/build_native.sh

Specific to Linux x86, ET runner segfaults on main, but succeeded prior to the PR https://github.com/pytorch/torchchat/pull/933.
- That specific PR fixes CUDA AOTI for llama 3
This diff expands the D_GLIBCXX_USE_CXX11_ABI to be explicit for both et and aoti. This allows for both the aoti build and et build to succeed.
---
Tested on Linux x86
```
./install_requirements.sh
scripts/build_native.sh aoti
python3 torchchat.py export llama3.1 --output-dso-path exportedModels/llama3-1.so
cmake-out/aoti_run exportedModels/llama3-1.so -z `python3 torchchat.py where llama3.1`/tokenizer.model -l 3 -i "Once upon a time" -d CUDA
export TORCHCHAT_ROOT=${PWD}
./scripts/install_et.sh
python3 torchchat.py export llama3.1 --quantize config/data/mobile.json --output-pte-path llama3-1.pte …
```

Explicitly set the D_GLIBCXX_USE_CXX11_ABI when building runners

---

README.md
cli.py
docs/model_customization.md

This adds an initial index for model customization options accessible from the README.
The introduced a "model_customization.md" that will be iterated and expanded upon over time
Note that some of the content is extracted/inspired by quantization.md and the ADVANCED_USERS docs, which are marked as outdated/unstable.
**README's**
https://github.com/pytorch/torchchat/blob/readme-model-customization-guide/README.md
https://github.com/pytorch/torchchat/blob/readme-model-customization-guide/docs/model_customization.md

README: Add a model customization guide

---

.github/workflows/run-readme-pr-mps.yml

By installing `llvm-openmp`, which prevents hang on the process shutdown due to the double loading of openmp library, that looks like a timeout in CI, see https://github.com/pytorch/torchchat/actions/runs/10101744183/job/27945942279 for example.
OpenMP from Anaconda interoperates nicely with the one bundled into the PyTorch.

Fix CI hang while running `test-readme-mps-macos`

---

.github/workflows/pull.yml

Some GH jobs that request MacOS are being given MPS machines, so the test cases attempt to MPS.
Issue is that MPS isn't available to via GH CI
This PR explicitly makes the tests use CPU
Tests that want mps/cuda should explicitly request for it
* There is separate infrastructure that allows access

CI: Explicitly use cpu when testing on GH machines

---

README.md

Will replace with a more intro friendly one

README: Remove Diagram

---

install_requirements.sh

Adds set -x for all installation commands in install_requirements.sh so that users can see what's actually being installed and can help debug when they run into any issues.
NOTE: This doesn't turn it on for all of the script (since that'd be overbearing) but rather turns it on specifically when installing things.
This also adds "set -eou pipefail" to the top of the script which is a recommended paradigm for all bash scripts since it adds things like error on exit, error on undefined variable, and propagation of errors on pipe failure.
https://explainshell.com/explain?cmd=set+-euo+pipefail

deps: Add set -x for installation commands

---

export.py

Summary: Read max_seq_length from model config instead of hard-code it

Update how AOTI export sets max_seq_length

---

generate.py

Prompt and num_samples were restricted from suppressed arg (always accepted as CLI arg even when not used by subcommand) to being restricted to `generate` in https://github.com/pytorch/torchchat/pull/987.
But this PR missed a call site. This updates the callsite that was missed to not access the field without checking for existence
Tested that both these commands no longer crash with accessing unavailable fields:
- python3 torchchat.py generate llama3.1
- python3 torchchat.py server llama3.1
Fixes: https://github.com/pytorch/torchchat/issues/1003

Fix GeneratorArgs to avoid unsafely accessing prompt and num_samples

---

docs/native-execution.md

docs: update native-execution.md

---

api/models.py
server.py

Implementation of the /models endpoint https://platform.openai.com/docs/api-reference/models
Start the server:
```
python3 torchchat.py server stories15M  
```
In another terminal:
```
curl http://127.0.0.1:5000/models
{"data": [{"id": "stories15M", "created": 1722531822, "owner": "puri", "object": "model"}], "object": "list"}
```
https://github.com/user-attachments/assets/16a7cc94-e678-4765-b090-5a94d21e2559

Openai api models endpoint

---

api/api.py
api/models.py
generate.py
server.py

Implement JSON formatted responses using OpenAI API types for server completion requests. Rather than giving single tokens at a time, the server will respond with a JSON following the API dataclasses corresponding to OpenAI API types. 
Testing:
Server 
```
python3 torchchat.py server stories15M   
```
Request (chunked)
```
curl http://127.0.0.1:5000/chat \
-d '{
"model": "stories15M",
"stream": "true",
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"content": "Story about a dog."
}
]
```
Request (synchronous)
```
curl http://127.0.0.1:5000/chat \
-d '{
"model": "stories15M",
"stream": "false",
"messages": [
{
"role": "system",
"content": "You are a helpful …
```

OpenAI API JSON formatted 

---

.ci/scripts/validate.sh
build/builder.py
cli.py
export.py

Summary: The --dynamic-shapes option will default to False. When the actual inputs are with static shapes, calling export with static shapes will make sure more Inductor optimizations take effect down the line. This change by itself improves average tokens/sec from 29.60 to 33.43 on A100. Some following PRs will provide further perf gains.
```
python3 torchchat.py export llama3 --quantize '{"precision": {"dtype":"bfloat16"}, "executor":{"accelerator":"cuda"}}' --output-dso-path /tmp/model16.so && python3 torchchat.py generate llama3 --dso-path /tmp/model16.so --prompt "Once upon a time," --max-new-tokens 256 --device cuda --num-samples 3
```

[AOTI] Add a --dynamic-shapes option to export

---

export.py

Summary: This improves average tokens/sec from 33.43 to 72.63 on A100 for AOTI.
```
python3 torchchat.py export llama3 --quantize '{"precision": {"dtype":"bfloat16"}, "executor":{"accelerator":"cuda"}}' --output-dso-path /tmp/model16.so && python3 torchchat.py generate llama3 --dso-path /tmp/model16.so --prompt "Once upon a time," --max-new-tokens 256 --device cuda --num-samples 3
```

[AOTI] Set sdpa_kernel context when exporting

---

README.md
server.py

Server routes were missing the "v1" portion. This is expected by OpenWebUI and other tools. See https://platform.openai.com/docs/api-reference/
Testing:
Run server
```
python3 torchchat.py server stories15M
```
In another terminal:
```
curl http://127.0.0.1:5000/v1/models
{"data": [{"id": "stories15M", "created": 1722531822, "owner": "puri", "object": "model"}], "object": "list"}%    
```
```curl http://127.0.0.1:5000/v1/chat \
-d '{
"model": "stories15M",
"stream": "true",
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"content": "Hello!"
}
]
}'
{"id": "621d4fc8-855e-4660-87af-3f2cf2a75a90", "choices": [{"delta": {"role": "assistant", "content": " She"}}], "created": 1722978694, "model": "stories15m", …
```

Add OPENAI_API_VERSION constant to routes

---

README.md
api/api.py
generate.py
server.py

**Implement [seed, temperature, max_tokens, system_fingerprint(partial)]** 
Improve determinism of generated responses. 
- seed: simply set torch.manual_seed() each time the seed is provided
- max_tokens: default to 16 as per API spec.
- temperature: default to 1.0 as per API spec.  
- system_fingerprint: for now, the backend and torch.dtype of the model weights. In the future, we should add model version information to this. 
Testing: With the same seeds, the generated response is the same. 
https://github.com/user-attachments/assets/7b186f86-5855-4b9e-92c3-cc617727c752
Tested with the following cURL:
```
curl http://127.0.0.1:5000/v1/chat \
-d '{
"model": "stories15M",
"stream": "true",
"max_tokens": "123",
"temperature": "0.2",
"seed": "813", …
```

Openai api completion params [seed, temperature, max_tokens, system_fingerprint]

---

torchchat/README.md

Introduces a torchchat top-level folder for us to move the current root directories into

[easy] Creating a torchchat folder for moving root directories

---

generate.py

Summary: use_tp was renamed to use_distributed in https://github.com/pytorch/torchchat/pull/873, but the PR missed generate.py, which caused "AttributeError: 'BuilderArgs' object has no attribute 'use_tp'" when running generate with --profile.

Rename use_tp to use_distributed

---

api/api.py
browser/browser.py
server.py

Ensure basic compatibility with OpenAI API via a Streamlit browser app. 
Using the examples on Streamlit's website, I've changed the browser app to query the torchchat OpenAI API server. I've added:
* Streamed responses
* Token limit
* Chat context reset button
https://github.com/user-attachments/assets/a1dabf4f-a801-4abf-9bf5-423f1a36d18e

Openai api compatibility

---

generate.py

This fixes the following assert that is easy to repro in any chat session:
```
Traceback (most recent call last):
File "/home/ubuntu/cali/torchchat/torchchat.py", line 69, in <module>
generate_main(args)
File "/home/ubuntu/cali/torchchat/generate.py", line 896, in main
for _ in gen.chat(generator_args):
File "/home/ubuntu/cali/torchchat/generate.py", line 748, in chat
self.chat_formatter.encode_header(
File "/home/ubuntu/cali/torchchat/generate.py", line 53, in encode_header
tokens.extend(self.tokenizer.encode(role, bos=False, eos=False))
File "/home/ubuntu/cali/torchchat/tokenizer/tiktoken.py", line 133, in encode
assert type(s) is str
```
I believe this regressed with https://github.com/pytorch/torchchat/pull/1035.

Fix assertion failure during chat session.

---

build/model_dist.py
dist_run.py

Re-pulling https://github.com/pytorch/torchchat/pull/1059 to merge into main because ghstack does not work with this repo.

Initial add of distributed model

---

build/model_dist.py
dist_run.py

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #1060
* #1059
PP + TP now working.

Add pipeline parallel

---

eval.py

**Issue** 
Inputs aren't set up correctly for .pte files. The input tensors must be static and cannot be reshaped. Currently, running eval will result in this error:
```
python3 torchchat.py eval llama3 --pte-path llama3.pte --limit 3    
...
Running loglikelihood_rolling requests
0%|                                                                                                                                                                                                         | 0/3 [00:00<?, ?it/s][tensor_impl.cpp:93] Attempted to resize a static tensor to a new shape at dimension 1 old_size: 1 new_size: 1263
[method.cpp:829] Error setting input 0: 0x10
0%| …
```

Fix eval for .pte

---

build/convert_hf_checkpoint.py
build/model_dist.py
dist_run.py
docs/ADVANCED-USERS.md

We created ModelArgs to replace the original TransformerArgs as the Arg entrance for torchchat model definition, but didn't fully updated because of incomplete ci coverage.
This PR updates torchchat download and serveral other parts to further migrate previous TransformerArgs into ModelArgs, to bring download back, as well as solve some potential issues.

Reenable torchchat download

---

build/gguf_loader.py
build/model_dist.py
eval.py
export.py
generate.py
quantization/quantize.py
torchchat/cli/builder.py
torchchat/cli/cli.py
torchchat/model.py
torchchat/usages/openai_api.py
torchchat/utils/build_utils.py

Specifically the file is renamed to build_utils

[Hackability Refactor] Move build/util into torchchat/utils

---

README.md
scripts/android_example.sh

Introduced in https://github.com/pytorch/torchchat/pull/1046, the `torchchat/edge` path header reflects the structure in the repo, but is unnecessary when abd'ing the android local path.
This PR just undo's that extra indirection

[easy] Undo Extra Redirection for adb Paths

---

dist_run.py
torchchat/model.py
torchchat/model_dist.py

The goal is to make the difference between `model.py` and `model_dist.py` as small as possible, and eventually consolidate them.
**[Consolidate TP]**
A first step is to move the parallelization code out from `.__init__()` into a separate `.distribute()` method, which is now an optional call:
```
model = Transformer(config)
model.distribute(tp_mesh)
```
`model.distribute` is a recursive call -- when hitting the child modules, it calls PyTorch's `parallelize_module` API with column-wise or row-wise styles. 
**[Consolidate PP]**
This is mostly cosmetic change -- naming `TransformerStage` back to `Transformer`, moving `stage_idx` into `config` etc.

[Consolidate] Move parallelization code into a .distribute() method

---

dist_run.py
torchchat/model_dist.py

Sequence parallel = Tensor parallel + dividing sequence by `tp_degree` at layer boundary
In addition to the op parallelism achieved by TP, SP reduces the activation size transferred between pipeline stages by `tp_degree`X.
The PR includes 4 parts:
1. Give SP styles to `parallelize_module` calls (this part mainly mimics what's used in torchtitan).
2. Before the attention layer, gather the sequence back.
3. Adjust example input to pipeline stages (divided by `tp_degree`).
4. Adjust the code for creating `input_pos` -- we still need to use the full seq length instead of `x.shape[1]` to create it bc `x` could have been cut in SP cases. 
Test:
`torchrun --nproc-per-node 8 dist_run.py`
(PP=2, TP=4)

[Distributed] Enable sequence parallel

---

dist_run.py
distributed/safetensor_utils.py

This PR:
1 - updates the q_proj and k_proj permuting to permute based on attn head dimensions (in line with torchchat main)
2 - updates the gating layer mapping to be w3 as well as remap w1 and w2 to correct up and down projection.
With these changes, we have full verification of 100% weight matching of all sampled weights when comparing stage weights to their subsection of single gpu weights ala:

safetensor updates: add attn head permute, update gating layer mapping

---

dist_run.py

This PR:
1 - addresses and fixes a mismatch that was present in distributed model vs single gpu where the rope embeddings were not an exact match.  
example:
~~~
5.4030e-01, 8.4147e-01.  (distributed)
Vs
5.3906e-01,  8.3984e-01. (single gpu rope)
6.4791e-01, 7.6172e-01
Vs
6.4844e-01,  7.6172e-01
7.3176e-01, 6.8156e-01
Vs
7.3047e-01,  6.7969e-01
~~~
The issue was we were creating the frequencies float32, and then later setting the model (llama2) to float16 to match the checkpoint dtype. 
The fix is to use torchchat set_precision and set that to torch.bfloat16 so that all cache creation happens in torch.bfloat16 and thus expected rope embeddings precision.

[distributed] ensure precise rope embeddings by creating frequencies in bf16

---

torchchat/cli/cli.py
torchchat/generate.py
torchchat/usages/eval.py

This PR is to add max-autotune for CPU in torch.compile. Meanwhile, split first token and next token in the log print.

Add max-autotune for CPU, update profile and fix next token calculation

---

torchchat/generate.py

Currently, in `torchchat/generate.py`, benchmarking time includes time for printing the table & saving Chrome-viewable trace, so incorrect performance data for `Total throughput` and `Next token throughput` is being printed when the PyTorch profiler is enabled. The difference is significant (only verified on CPU. With int8 weight-only quantization, it resulted in a difference of 9 tokens/second, perhaps because I had also enabled shapes & memory profiling, which would've increased the size of the trace).
For verification, manually enabled profiling in `generate.py` because using `--profile` argument with `torchchat.py` did not work with HEAD commit 64510a33cd09b67b411e939ae0953d403724113c. I'm guessing its support is WIP.

Fix benchmarking statistics computation when profiler is used in generate.py

---

dist_run.py
distributed/parallel_config.py
distributed/utils.py

This PR:
1 - adds a GPUMemoryMonitor class to:
a - log the gpus' device capabilities at start of run (in yellow):
b - at the end of the run, show the absolute peak res memory as well as % peak memory used per stage:

[distributed] add gpu specs, % and absolute peak mem used per stage

---

dist_run.py
distributed/utils.py

This PR:
1 - adds a TrackTimer class to wrap perf_counter and make it easy to do perf timings.
2 - implements it to track weight loading time per stage:
Note - there is a similar timer class called measure_time in chat, but I added some additional rounding options,  unit options and also didn't want to use print for the logging.

[distributed] add TrackTime, CUDATrackTime to monitor perf for weight loading per stage and future perf measurements

---

dist_run.py
distributed/__init__.py
distributed/config_manager.py
distributed/dtensor_utils.py
distributed/logging_utils.py
distributed/parallel_config.py
distributed/parallelize_llama.py
distributed/safetensor_utils.py
distributed/utils.py
distributed/verification_utils.py
distributed/world_maker.py

This PR:
1 - adds a new SingletonLogger to eliminate an issue that was popping up with duplicate logging. 
Before:
After:
2 - This logger adds a couple useful formatting improvements:
a - option to not display the year in the timestamp to save space
b - avoid putting INFO / DEBUG for the level, again to save space (WARNING / ERROR / CRITICAL) are always shown
c - shows the calling filename and line number even though this is now a singleton setup
d - strips ".py" extension so that it's filename:line_number and not filename.py:line_number, again to save space.

[distributed] add SingletonLogger to avoid duplicate logging, with custom formatting options including file name: line_number

---

dist_run.py
distributed/utils.py

This PR:
1 - computes the total params per stage and total byte size, and presents that in a nicely formatted manner:
There are four underlying functions supporting this - one each for getting the relevant data, and then one each for formatting it nicely into a nice human readable format. 
The result is we can quickly monitor / verify that stages are relatively balanced in params / size.

[distributed] add stage metrics - total params per stage, total size and present it in a nicely formatted manner

---

torchchat/model.py
torchchat/model_params/Meta-Llama-3-70B.json
torchchat/model_params/Meta-Llama-3-8B.json
torchchat/model_params/Meta-Llama-3.1-70B.json
torchchat/model_params/Meta-Llama-3.1-8B.json

1) Previously the block_size was not being included in the model_params.json of llama3/3.1 models so it just used a hard coded 2048. This PR adds them into the config.
2) For rope_scaling (llama 3.1), we were hardcoding the parameters inside of `apply_scaling()` instead of taking them in as TransformerArgs built from model_params. These happen to line up for 3.1, but this PR makes them an explicit read

Add missing Block size + Update Configs to not hardcode rope_scaling

---

README.md

Miscellaneous README fixes + the server instructions out of a hidden dropdown (removes a click for testing browser)

README: Minor typos + Upsell Server

---

install/install_requirements.sh
torchchat/cli/builder.py
torchchat/model.py

As torchao 0.5.0 released with mac prebuilt, we update installation script to enable torchtune across different platform

bump ao to 0.5.0 to enable torchtune across platforms

---

.github/workflows/pull.yml
torchchat/cli/builder.py
torchchat/cli/cli.py
torchchat/generate.py
torchchat/model.py

Tested using:
```
python3 torchchat.py generate --checkpoint-path ~/path/to/consolidated.pth --tokenizer-path ~/path/to/tokenizer.model --params-path ~/path/to/flamingo.json --image-prompts ~/path/to/dog.jpg --prompt "Is the image of a cat?"
```
Chat does not function properly with image prompts.

Torchchat CLI pipeline for Multimodal Models

---

dist_run.py

Add argparser to accept model name and other arguments (e.g. PP degree).
```
$ torchrun dist_run.py -h
usage: dist_run.py [-h] [--pp PP] {llama2-7b-chat,llama3}
positional arguments:
{llama2-7b-chat,llama3}
Name of the model to load
options:
-h, --help            show this help message and exit
--pp PP               Pipeline parallel degree
```
Supported model names:
```
llama2-7b-chat
llama3
```
(Following model aliases in [models.json](https://github.com/pytorch/torchchat/blob/main/torchchat/model_config/models.json))
Renamed variable `hf_model_name` to `distribution`.
A distribution looks like this:
`meta-llama/Llama-2-7b-chat-hf`
`meta-llama/Meta-Llama-3-8B-Instruct`
Fix `output` undefined error when PP = 1.

[Distributed] Accept model names

---

dist_run.py

When there is only 1 PP stage, we can skip the sendrecv.
Plus some cleanup and renaming.

[Distributed] fix pp=1 case; clean up

---

dist_run.py

Accommodate review comments of previous PR:
avoid calculating these IDs multiple times.

[Distributed] Move global id calculation

---

dist_run.py
run_dist.sh

This PR:
1.  enables batch decoding such that multiple prompts can be run and processed at the same time. 
2. moves the dst/src calcs for pp comms out of the decoding loop
3. updates final display to show each respective prompt and result. 
4. Tested with both PP=1 and PP=2

[distributed] add batch decoding 

---

torchchat/generate.py
torchchat/usages/browser.py
torchchat/usages/openai_api.py
torchchat/usages/server.py

As described, tested with a basic image input.

UI and API implementation for base64 encoded image input

---

torchchat/cli/convert_hf_checkpoint.py

Side effect of https://github.com/pytorch/torchchat/commit/964d43713bd993fc81cec71a6043b22550580692 was that ModelArgs was updated to the following
```
ModelArgs.transformer_args: Dict[str, Dict[str, Any]]
```
The checkpoint translation requires the field from TransformerArgs, so this creates an explicit object from the config

Converting transformer_args to explicit object for checkpoint construction

---

torchchat/cli/cli.py

These are fields that were already supported in torchchat, but were simply suppressed in the help menu.
This just unsurpassed them
> python3 torchchat.py generate --help
``` 
usage: torchchat generate [-h] [--checkpoint-path CHECKPOINT_PATH] [--params-path PARAMS_PATH]
[--tokenizer-path TOKENIZER_PATH] [--compile] [--compile-prefill]
[--dtype {fp32,fp16,bf16,float,half,float32,float16,bfloat16,fast,fast16}] [--quantize QUANTIZE]
[--device {fast,cpu,cuda,mps}] [--dso-path DSO_PATH | --pte-path PTE_PATH] [--prompt PROMPT]
[--num-samples NUM_SAMPLES] [--image-prompts IMAGE_PROMPTS [IMAGE_PROMPTS ...]]
[--max-new-tokens MAX_NEW_TOKENS] [--top-k TOP_K] [--temperature TEMPERATURE] [--max-autotune]
[--hf-token HF_TOKEN] [--model-directory MODEL_DIRECTORY] [-v] [--seed SEED]
[model]
options:
-h, …
```

Unsupress params and tokenizer path in CLI

---

dist_run.py

#1153 made a change that `ModelArgs.transformer_args["text"]` is now a dict. 
We need to convert the dict into `TransformerArgs` using `TransformerArgs.from_param(...)`.
Potential TODO:
Create model instead of creating the inner Transformer.

[Distributed] Follow upstream TransformerArgs changes

---

dist_run.py
torchchat/model.py

SP is one step further than TP in that it further distributes the layer norm computation.
There are a couple reason to turn the dial back to pure TP:
(1) LLM inference has a prefill phase and a decoding phase which have different seqlen. The decoding phase has a seqlen of 1, to which SP cannot be applied. We don't want to create two models and apply SP and TP separately.
(2) The major motivation of SP is to reduce activation envelope. While this is important in training (bc backward needs those intermediates), we are using `torch.no_grad()` in inference, in which case activations are not kept anyway.
(3) While it is true that AllReduce = AllGather + ReduceScatter, in small-size region latency dominates, so launching 1 collective may be better than launching two collectives. 
- Removed SP …

[Distributed] Use Tensor Parallel instead of Sequence Parallel

---

dist_run.py

Prefill phase and decoding phase are now done separately.
Decoding phase will leverage KV cache and speed improves.
Requires a PyTorch side fix to work. Will change the pin version.
Requires pytorch PR https://github.com/pytorch/pytorch/pull/136243 to land.
Otherwise, you may hit issue described in: https://github.com/pytorch/pytorch/issues/136225

[Distributed] Separate prefill and decode

---

torchchat/cli/builder.py

General typehints in builder.py
Code changes to call out:
* Dropped unused arg `only_config` from load signatures
* Removed redundant default fields in `TokenizerArgs`

Removed unused only_config arg; Added typehints to builder

---

torchchat/model.py

As titled, torchchat expects logits as (1, 1, vocab size), but depending on the exporting logic the batch dim is not provided (for example with pte generated from the ET repo
This just adds a simple check and layer if needed.
Tested by 
```
python3 torchchat.py generate llama3.1 --pte-path <pte from ET repo export>
python3 torchchat.py generate llama3.1 --pte-path <pte from TC repo export>
```

Fix support for ET repo generated pte by optionally adding batch dim

---

torchchat/cli/builder.py

Currently, when loading a `.pte` file is provided, the base model is loaded in order to obtain the `model.config: ModelArgs`. This is overkill (and is not resolved in this PR) since the rest of the base model is discarded. 
This PR avoids this wasteful loading in one condition: a manual `params_path` is provided, which can be used to construct ModelArgs
---
Tested by passing in a pte w/ and without a manual param 
```
python torchchat.py generate llama3.1 --pte-path model.pte
- Load
python torchchat.py generate llama3.1 --pte-path model.pte --params-path config.json
- No Load
```

Improve pte loading when given manual params_path

---

dist_run.py
torchchat/export.py
torchchat/model.py

KV cache is extended to have multiple lanes, each letting a separate batch pass through, achieving pipeline parallelism.
1. `setup_caches` will take one kwarg `cache_lanes` (default to 1).
```
def setup_caches(self, max_batch_size, max_seq_length, cache_lanes: int = 1)
```
2. `attention.kv_cache` is now a `nn.ModuleList`, containing multiple `KVCache`'s, each corresponding to a lane.
3. We now pass `kwargs = {"input_pos": input_pos, "cache_lane": lane}` to the `step()` function. Removing the temporary helper function `model.setup_input_pos`.
Requires https://github.com/pytorch/pytorch/pull/136416 to support pass-in of kwargs.

[Distributed] Add lanes to KV cache

---

runner/run.cpp

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #1171
* #1170
* __->__ #1186
* #1184
* #1169
* #1168
* #1181

Also use default max_seq_length of 128 for ExecuTorch native runner

---

torchchat/export.py
torchchat/model.py

Previous PR https://github.com/pytorch/torchchat/pull/1174 has two issues:
(i) Wrong default `cache_lane` value given to forward function (should be 0, gave 1).
(ii) Did not add cache lane impl to `CustomKVCache`. The impl is required if we want the KVCache to CustomKVCache replacement work smoothly.

[Distributed] Fix cache lane

---

torchchat/export.py

Reverts pytorch/torchchat#1193 -- trunk runner-et job https://github.com/pytorch/torchchat/actions/runs/11022084837/job/30610612304 is showing garbage output for fp16 and bf16, previous job had normal output. I suspect that #1193 fixes a real bug that was covering up a different bug, though; will investigate.

Revert "export.py: fix custom SDPA type conversion logic & re-enable for bfloat16"

---

runner/run.cpp

The native runner incorrectly assumed that the output of the model
must always be float. Now it doesn't.

native runner: convert logits to float

---

runner/run.cpp
torchchat/export.py

This reapplies #1193 now that the native runner is fixed. We should
pay special attention to the runner-et job on this PR to make sure the
output is good.

Revert "Revert "export.py: fix custom SDPA type conversion logic & re-enable for bflo…" (#1197)"

---

dist_run.py

Decoding tensor-form token ids to strings involves a CPU sync.
This PR added a flag to disable on-the-flight conversion.
```
torchrun --nproc-per-node 4 dist_run.py llama2-7b-chat --pp 2 --disable-in-flight-decode
```

[Distributed] Make decode in flight optional

---

torchchat/cli/builder.py

As titled. The Flamingo model was initialized in meta. Then
- load checkpoint with 1x weight size
- model is initialized again (probably to populate the buffers in rotary embedding), with another 1x of weigth size.
So for a model with 21 GB weight size, the memory usage is 42 GB after model loading. 
Context:
Buffers in rotary embedding are not included in the checkpoint.
Instead, they are calculated in initialization. Since buffers on meta device
does not host any actual values, need to reinitialize them in the actual
device. 
Fix: 
Only do those buffer initialization, without initializing the entire model.
Peak memory:
max_seq_len = 128: Before: 43.57 GB after: 28.55 GB
max_seq_len = 8192: Before: 45.47 GB after: 30.5 GB

[Flamingo] Fix the memory usage of 2x checkpoint size after loading

---

.gitignore
install/install_requirements.sh
torchchat/generate.py
torchchat/model.py

Torchtune updates flamingo model definition, as well as its inference. This PR aims to update torchchat pipeline to sync with torchtune

Bump torchtune pin to a 9-24 commit; Update Flamingo Definition 

---

torchchat/cli/builder.py

We use a new rope class after bumped tune version.

Update Flamingo Builder to use Llama3ScaledRoPE instead of RotaryPositionalEmbeddings

---

torchchat/usages/openai_api.py

Start the server by either specifying the model 
```
python3 torchchat.py server llama3.2-11B
```
**or** by specifying paths for the checkpoint
```
python3 torchchat.py server --checkpoint-path ../llama_3.2_11b/consolidated.pth --tokenizer-path ../llama_3.2_11b/tokenizer.model --params-path torchchat/model_params/Llama-3.2-11B-Vision.json
```
python3 torchchat.py server 
Use this curl command to test
```
curl http://127.0.0.1:5000/v1/chat/completions \
-d '{
"model": "llama3.2",
"messages": [
{
"content": [
{
"type": "text",
"text": "What'\''s in this image?"
},
{
"type": "image_url",
"image_url": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAG0AAABmCAYAAADBPx+VAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAA3VS …
```

OpenAI API: Changes to enable multi-modal for 3.2 11B

---

torchchat/generate.py

This PR enables llama3.2-11b model with text-only input.
Note that this PR is only for CLI pipeline. Will have a separate PR for openai-api update
```
(torchchat-test) [gasoonjia@server ~/torchchat-32mm (main|REBASE-i|main)]$ python torchchat.py generate llama3.2-11B --prompt "How are you these days"
Using device=cuda NVIDIA PG509-210
Time to load model: 8.88 seconds
How are you these daysI'm just a computer program, so I don't have feelings or emotions like humans do, but thanks for asking! I'm functioning properly and ready to assist with any questions or tasks you may have. How about you? How's your day going?
========================================
Average tokens/sec (total): 11.66                 
Average …
```

support text-only input with llama3.2-11b

---

torchchat/generate.py
torchchat/usages/openai_api.py

Before this diff, openai api and cli has their own pipeline to convert the user's input into model's input. We have to maintain both of them to make them up-to-date.
This PR unifies the model input generation pipeline to make openai api support text-only input, just like cli right now, and makes the pipeline more stable and maintainable.

Unify Input Generation for CLI and Openai API

---

torchchat/utils/quantize.py

As titled, originally the message was shown regardless of whether the scheme was used; tested on Mac (ARM)
---
Not Using Quant
```
> python3 torchchat.py generate llama3.1 --device cpu
Using device=cpu Apple M1 Max
Time to load model: 2.24 seconds
```
---
Using Quant 
```
> OMP_NUM_THREADS=6 python3 torchchat.py generate llama3.1 --device cpu --dtype float32 --quantize '{"linear:a8wxdq": {"bitwidth": 4, "groupsize": 256, "has_weight_zeros": false}}'
```
w/o Loading
```
Using device=cpu Apple M1 Max
Time to load model: 2.74 seconds
Quantizing the model with: {'linear:a8wxdq': {'bitwidth': 4, 'groupsize': 256, 'has_weight_zeros': False}}
Time to quantize model: 0.00 seconds
Traceback (most recent …
```

Raise a8wxdq load errors only when quant scheme is used

---

torchchat.py

Issue: https://github.com/pytorch/torchtune/issues/1723
---
Test
```
python torchchat.py server llama3.2-11B
```
```
```
Then submit a large image

Add MPS Fallback to support torchtune Multimodal MPS

---

torchchat/cli/cli.py

No Compile, No Warning
```
python torchchat.py generate llama3.1
Using device=mps
Time to load model: 10.68 seconds
```
With compile, with Warning
```
python torchchat.py generate llama3.1 --compile
Warning: compilation is not available with device MPS, ignoring option to engage compilation
Using device=mps
Time to load model: 11.98 seconds
```

Only show MPS Compile Warning if compile is attempted

---

torchchat/usages/openai_api.py

Refactor introduced in https://github.com/pytorch/torchchat/commit/8278aa26fff3ac0162b7eaafe4dc41445f94d867 prevented non multimodal models (e.g. 3.1 8B) from doing multiturn in borswer/openai api.
This re-enables it via casing out MM (LLama3.2 11B). Support for 11B Multiturn and reunification of logic will be in followup PRS
---
Tested via Browser
```
python torchchat.py server llama3.2-11B 
python torchchat.py server llama3.2-1B 
```
Then test in browser with 1B (Text only - Saw it can do multiturn) and 11B (Multimodal - No multiturn as expected)
```
```

Fix non-MM multiturn: Use legacy formatting

---

torchchat/generate.py
torchchat/usages/openai_api.py

Refactor the OpenAI parsing logic for non-MM dialog into `_gen_model_input` of generate.py
---
Tested via Browser
```
python torchchat.py server llama3.2-11B 
python torchchat.py server llama3.2-1B 
```
Then test in browser with 1B (Text only - Saw it can do multiturn) and 11B (Multimodal - No multiturn as expected)
```
```

Absorb non-MM OpenAI dialog parsing into generic input parsing

---

dist_run.py
torchchat/distributed/dtensor_utils.py
torchchat/distributed/safetensor_utils.py

Changing from:
```
with device:
model = Transformer(config)
```
to
```
with torch.device("meta"):
model = Transformer(config)
```
because when we later load weights, we will swap out the tensors of the model anyway. So saving an on-device init here.
Also added a `with device` context to `model.setup_cache()` call. So that the caches are directly created on the target device -- saving a `model.to(device)` call.

[Distributed] create model on meta device

---

dist_run.py

TP-only case is broken due to the following error:
```
[rank1]:   File "/home/kw2501/local/torchchat/torchchat/model.py", line 815, in forward
[rank1]:     bsz, seqlen, _ = x.shape
[rank1]: ValueError: not enough values to unpack (expected 3, got 2)
```
```
[rank3]:   File "/home/kw2501/local/torchchat/dist_run.py", line 477, in main
[rank3]:     output = decorder.step(new_token, **kwargs)
[rank3]:   File "/home/kw2501/local/pytorch/torch/distributed/pipelining/schedules.py", line 610, in step
[rank3]:     self._step_microbatches(args_split, kwargs_split, targets_split, losses)
[rank3]:   File "/home/kw2501/local/pytorch/torch/distributed/pipelining/schedules.py", line 710, in _step_microbatches
[rank3]:     output = self._stage.forward_one_chunk(i, arg_mbs[i], kwarg_mbs[i])  # type: …
```

[Distributed] Fix new token's shape

---

.lintrunner.toml
CONTRIBUTING.md

Lintrunner is currently broken since the .lintrunner.toml was moved to the install directory. 
This PR updates the necessary paths & moves .lintrunner.toml back to the top-level directory so that lint changes can be applied. 
I also provide basic instructions on linter installation & usage in the CONTRIBUTING.md.
Tested using a fresh venv as follows:
```
python3 -m venv .venv                            
source .venv/bin/activate
./install/install_requirements.sh
pip3 install -r install/requirements-lintrunner.txt
```
```
(.venv) puri@puri-mac torchchat % lintrunner -a
Warning: Could not find a lintrunner config at: '.lintrunner.private.toml'. Continuing without using configuration file.
ok No lint issues.
Successfully applied all patches.
```

Move .lintrunner.toml to top-level directory and include basic linting instructions in CONTRIBUTING.md

---

dist_run.py
torchchat/distributed/safetensor_utils.py

`TiktokenTokenizer` (used by llama3) and `SentencePieceProcessor` (used by llama2) seem to have different requirement on input shape (1D list or 2D list).
Adding a condition to separate the input prep for the two.
Also improved some logging.

[Distributed] Fix tiktokenizer decoding

---

torchchat/cli/convert_hf_checkpoint.py
torchchat/cli/download.py
torchchat/model_config/model_config.py

Closes #1249
This PR implements support for downloading and converting model checkpoints from `huggingface` which use the `safetensors` format rather than the `pth` binary (pickle) format.
* Allow the tensor map file to be found under different `*.index.json` names
* Allow loading model files with `safetensors.torch.load` when needed
* Allow downloading safetensor files if they exist without pth files or the model explicitly prefers them
* I have tested that the download and load for `llama3.1` are un-changed with these changes (no `safetensors` are downloaded)
* I have verified (on my [WIP branch for Granite Code](https://github.com/gabe-l-hart/torchchat/tree/GraniteCodeSupport
)) that for models with only `safetensors`, they are not ignored and can be cleanly converted

Safetensors

---

torchchat/generate.py
torchchat/usages/browser.py
torchchat/usages/openai_api.py

Multi-turn conversations were not working within the browser for LLaMA 3.2 Vision. This fixes this for the case of: 
- Text only conversation
- Conversation with one image prompt.
| Model | Browser Test Text Only | Browser Test with Image | Generate CLI test |
| -------- | ------- | ------ | ------ |
| LLaMA 3.1 | ✅ | - | ✅ | 
| LLaMA 3.2 11B Vision | ✅ | ✅ | ✅ |
```
python3 torchchat.py generate llama3.2-11B --prompt "What's this?" --image-prompt assets/dog.jpg
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/data/metrics/__init__.py:19: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 1.23.2)
from scipy.stats import pearsonr, spearmanr
2024-10-04:18:39:09,981 INFO …
```

Multiturn mm single image

---

dist_run.py

This PR is minor:
1 - adds an enum for TokenType so that we can better handle various tokenizer types directly. 
2 - renames decorder to decoder for clarity.

[Distributed] add TokenizerType enum, spelling

---

torchchat/generate.py

Flagging  `GeneratorArgs.is_torchtune_model` as a misnomer since it doesn't capture all torchtune models (i.e. Flamingo)
* Issue: https://github.com/pytorch/torchchat/issues/1273
This PR also reverts the commenting out of a snippet of code in https://github.com/pytorch/torchchat/commit/d0993b3508f802e81a6917b8959907a9abff827a which was done to unblock Flamingo support, but affected non-torchtune behavior
---
Verified `python torchchat.py generate llama3.2-11B --prompt "What's in this image?" --image-prompt assets/dog.jpg`
Verified `python torchchat.py generate llama3.2-11B`
Verified `python torchchat.py generate llama3.2-1B`

Flag misnomer: GeneratorArgs.is_torchtune_model

---

torchchat/generate.py
torchchat/usages/browser.py
torchchat/usages/openai_api.py

LLaMA2 Chat Formatter doesn't accept list-type message content. Since none of the LLaMA2 models are multimodal, we can be sure that the content type will be text. Simply forward the first text content of the message to the model
Tested using:
```
python3 torchchat.py server llama2   
```
and
```
```

LLaMA 2 Chat Formatter List Message Content Fix

---

install/install_requirements.sh

On ROCm systems, running this script will not set up PyTorch with ROCm compatibility. This change should make users' experience smoother on AMD GPU systems. Will test on an AMD GPU system & update PR

Add check for rocminfo in the installation script to replace the nightly URL with the appropriate ROCm whl.

---

torchchat/distributed/checkpoint_utils.py

Some HF format uses index + multiple binaries instead of index + multiple safetensors.
Distributed workflows already support the later, this PR adds support for the former too. 
(The reason is that quantized checkpoint cannot save as safetensor format yet.)

[Distributed] Support index + multi-bin loading

---

torchchat/utils/quantize.py

Remove duplicate priority logic to make code at cli.py:485 the single authoritative priority selection logic between options present in both quantize settings and cli

remove duplicated quantize_config vs cli priority logic from quantize.py

---

torchchat/cli/convert_hf_checkpoint.py
torchchat/model.py

This PR is part of a sequence in support of adding Granite Code. It depends on merging the following PRs:
Closes #1250
This PR adds support for models which have `bias` tensors for the attention and ffn modules alongside the primary weight tensors.
* Add the bias tensors to the `weight_map` in HF checkpoint conversion
* Handle merged `wqkv` tensors for bias as well as weights in HF checkpoint conversion
* This includes changes to the permutation logic to support the shapes of the bias tensors. I leveraged the corresponding logic in [llama.cpp's converter](https://github.com/ggerganov/llama.cpp/blob/master/convert_hf_to_gguf.py#L1569).
* Add configs to `TransformerArgs` to allow models to indicate the presence of `attention_bias` and `feed_forward_bias` tensors
* Populate the `Attention` …

Bias tensors

---

torchchat/model.py

This PR is part of a sequence in support of adding Granite Code. It depends on merging the following PRs:
Closes #1252 
This PR adds support for models which have shared weights between the input word embeddings and the output layer (tied word embeddings).
* Add the `tie_word_embeddings` parameter to `TransformerArgs`
* Add a `load_hook` to the `Transformer` class where, if configured with `tie_word_embeddings`, the `self.output` module will share weights with the `self.tok_embeddings` module.
In conjunction with my other changes for Granite Code, I've been able to validate that the results produced with this logic do produce the expected token sequence.
NOTE: If there's any preferred way to include unit tests along with the PR, please let me know and I can get them added! I don't see a …

Tied word embeddings

---

torchchat/generate.py

Based on https://github.com/pytorch/torchtune/blob/57ab583c84c4a9dcacac23aeabc81f2a679670fe/torchtune/training/_compile.py#L42-L52
Compile as much of the Llama3.2 11B Vision Model from tune as we can
---
Testing:
```
python torchchat.py generate llama3.2-11B --prompt "What's in this image?" --image-prompt assets/dog.jpg --compile
```
Run it a few times to avoid caching times: On the 4th iteration
```
What's in this image?The image is of a dog wearing sunglasses and riding a skateboard in the street. The dog is white with some brown spots on its face and ears, and it has its tongue out. It's wearing red sunglasses and a blue collar, and its front paws are on a red penny board with yellow wheels. The background is a road with green trees on either side.2024-10-09:18:43:33,307 INFO …
```

Add Initial Compile for Llama 3.2 11B: Decoder TransformerSelfAttentionLayer, TransformerCrossAttentionLayer

---

torchchat/utils/scripts/android_example.sh

Should be torchchat/edge/android/torchchat

Update Android app path

---

torchchat/generate.py

Minor QoL change; push the formatting of text string prompts into the helper
---
Tested via browser: 
```
python torchchat.py server llama3.2-11b
```
Tested in CLI
```
python3 torchchat.py generate llama3.2-1b
Using device=cuda NVIDIA PG509-210
Time to load model: 1.55 seconds
Hello, my name is Jane Doe and I am a citizen of the United States. I am a survivor of a violent crime, and I am reaching out to seek support and resources.
Please note that I am not a victim of a violent crime, but I am still seeking help and guidance. This is a difficult time for me, and I want to know that I have the support and resources that I need. I am a citizen of the United States and I am …
```

Push Message formatting into _gen_model_input

---

install/requirements.txt

Fix #1296
Align with https://github.com/pytorch/pytorch/blame/main/requirements.txt#L5

Remove numpy < 2.0 pin to align with pytorch

---

install/install_requirements.sh

Update torchtune pin to 0.4.0-dev20241010 . This is the newest version visible to the ROCm wheel & fixes the installation script for AMD/ROCm systems (otherwise, it would break since 0.3.0-dev20240928 isn't visible via the ROCm 6.2 wheel)
pip list after running install_requirements.sh successfully.
```
pip list 
Package                   Version
------------------------- --------------------------
absl-py                   2.1.0
accelerate                1.0.1
aiohappyeyeballs          2.4.3
aiohttp                   3.10.10
aiosignal                 1.3.1
altair                    5.4.1
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.6.2.post1
async-timeout             4.0.3
attrs                     24.2.0
blinker                   1.8.2 …
```

Update torchtune pin to 0.4.0.dev20241010

---

install/requirements.txt

Setting numpy version to be the range required by gguf: https://github.com/ggerganov/llama.cpp/blob/master/gguf-py/pyproject.toml

Unbreak gguf util CI job by fixing numpy version

---

torchchat/cli/download.py

This PR:
1 - removes the now obsolete local_dir_use_symlinks from the hf snapshot_download api call.  
2 - this then removes the currently displayed long warning about using it which is shown to the user when running torchchat.py download...
Before this PR:
~~~
[less@devgpu011.cco3 /data/users/less/local/chatmaster (main)]$ python torchchat.py download llama3
Downloading meta-llama/Meta-Llama-3-8B-Instruct from HuggingFace...
/home/less/local/miniconda3/envs/newserver/lib/python3.10/site-packages/huggingface_hub/file_download.py:1212: ****UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. 
The process to download files to a local folder has been updated and do not rely on symlinks anymore. 
You only need to pass a destination folder as`local_dir`.
For more …

[downloads] remove obsolete hf param for using symlinks (local_dir_use_symlinks=False,) and avoid showing warning about it

---

.ci/scripts/run-docs
torchchat/utils/scripts/updown.py

warn about unmatched skip markup in docs run thru updown processor (processing test markup for markdown files) 
cc: @swolchok

Detect unmatched skip begin/end commands

---

torchchat/cli/builder.py

Beautify a series of similar checks & fix a spelling error.

Minor cleanup in torchchat/cli/builder.py

---

torchchat/utils/build_utils.py

Add docstrings build_utils.py, enforce consistent precision answers over a single run

Add docstrings build_utils.py, enforce consistent precision answers over a single run

---

torchchat/generate.py

TPS and other stats were being reported as NAN due to poor logic. 
I don't see any reason why compile should block theses stats from being printed or why there should be a separate TPS for jit compile
```
python3 torchchat.py generate llama3.2-1b --compile --device cuda
Using device=cuda NVIDIA PG509-210
Time to load model: 1.19 seconds
Hello, my name is Sophia. I'm a huge fan of your work. I've been following your blog for a while now and I just wanted to say that your content is top-notch. I love how you share your passion for history, science, and culture with your audience.
As a young woman in my early twenties, I'm always looking for new and interesting things to read about. Your blog is the perfect place to …
```

Remove if statement preventing tps stats from being printed when running generate with compile

---

README.md

add slack channel to readme

---

tokenizer/base.py
tokenizer/hf_tokenizer.py
tokenizer/tiktoken.py
tokenizer/tokenizers.py
torchchat/cli/builder.py
torchchat/model.py

This PR is part of a sequence in support of adding Granite Code. It depends on merging the following PRs:
Closes #1251 
This PR adds partial support for models that use the `tokenizers` (as opposed to `tiktoken` or `sentencepiece`) for tokenization. This PR only addresses support in the `python` runner, and it does so by creating a new class in the `tokenizer` module that simply wraps `tokenizers`.
I'm not sure this is the correct direction to go for solving this since the `tokenizers` library is not (to the best of my knowledge) portable to the various export formats (yet). There are two main challenges to extending more tokenizer support outside of simply wrapping `tokenizers`:
For may tokenizers, multiple regexes are used in sequence to split the raw string. Not being a regex expert …

Tokenizers tokenizer

---

torchchat/export.py
torchchat/utils/build_utils.py

2 mini fixes on https://github.com/pytorch/torchchat/pull/896
* Enum logic typos (was not found when testing originally due to Python magic)
* max_seq_len discrepancy (found when testing)
```
python3 torchchat.py export llama3.1 --quantize '{"precision": {"dtype":"bfloat16"}, "executor":{"accelerator":"cuda"}}' --output-aoti-package-path /tmp/model3.pt2
python3 torchchat.py generate llama3.1 --aoti-package-path /tmp/model3.pt2 --prompt "Once upon a time,"  --num-samples 3
```
Compared to 
```
python3 torchchat.py export llama3.1 --quantize '{"precision": {"dtype":"bfloat16"}, "executor":{"accelerator":"cuda"}}' --output-dso-path /tmp/model3.so
python3 torchchat.py generate llama3.1 --dso-path /tmp/model3.so --prompt "Once upon a time,"  --num-samples 3
```

Minor fixes to PT2 export path: enum typo and max_seq_len

---

torchchat/cli/cli.py
torchchat/cli/convert_hf_checkpoint.py
torchchat/utils/build_utils.py

Closes: https://github.com/pytorch/torchchat/issues/1347
Import torch lazily in all places used by the CLI that don't need a model
These changes add a little complexity with the lazy and local imports, but they also greatly improve the CLI's response for `--help`, `list`, and `where`.
**Changes:**
* Move `import torch` into function bodies that need them
* Use `importlib.metadata.version` to check the torch version rather than torch.__version__
* Switch from using torch.inference_mode as a decorator to using it as a context manager.
* I also removed it from convert_hf_checkpoint_to_tune since that does not use torch at all
* In build_utils, wrap the dtype values in lambdas so they're lazily fetched.

Fast non-model CLI commands

---

torchchat/usages/openai_api.py

Some Chinese characters require more than two or three tokens to decode, tokens will be decoded immediately, rather than wait for two or three tokens.
Current output:
Fixed output:

Fix error: characters can not be displayed normally in chinese

---

install/install_requirements.sh

4246c57b fix: enforce python version
commit 4246c57bb58891cedd61833c1212deb4b6ee0d69
Date:   Wed Nov 6 10:30:24 2024 +0100
fix: enforce python version
The previous Python version check was incorrect, allowing installations
on unsupported interpreter versions, which caused installation failures.
Additionally, we now respect the specified interpreter version if
provided, consistently using it throughout the installation process by
enforcing it with pip.

fix: enforce python version

---

torchchat/cli/builder.py
torchchat/generate.py

This PR removes the last references to the use_distributed argument which got replaced by --distributed

Remove last references to use_distributed argument

---

torchchat.py

a6dcfc59 fix: add SIGINT handler
commit a6dcfc59b3fa5f16b207f3cf38aee5d8f18a08e9
Date:   Thu Nov 7 14:18:21 2024 +0100
fix: add SIGINT handler
Setup a SIGINT handler to gracefully exit the program once the user
presses ctrl+c.

fix: add SIGINT handler

---

torchchat/cli/cli.py

Users may expect that cli parameters override the JSON, as per #1278.   Confirm the inverted behavior suggested by #1278 is what we want.  Also, if we do, then for sanity, we should apply the same priority scheme to both dtype and device values.
Invert logic - case split: 
1 - if none (no value) is specified, use value specified in quantize dict, if present; else 
2 - if value is specified, override the respective handler if present.

Update cli.py to make --device/--dtype pre-empt quantize dict-specified values

---

torchchat/generate.py

When the model cache is already set up, there is no need to call `setup_caches` each time a sample is passed in.
This is normally fine, but torchtune is noisy (as it should) when setup_cache is unnecessarily called.
This just adds a check for first sample
---
Warnings that are now missing
```
Key value caches are already setup. You cannot call ``setup_caches()`` twice. Skipping.
Key value caches are already setup. You cannot call ``setup_caches()`` twice. Skipping.
Key value caches are already setup. You cannot call ``setup_caches()`` twice. Skipping.
Key value caches are already setup. You cannot call ``setup_caches()`` twice. Skipping.
```
Generation after fix (no warning)
```
python torchchat.py generate llama3.2-11B --prompt "What's in this image?" --image-prompt assets/dog.jpg …
```

Update Caching logic to only trigger on the first inference sample

---

install/install_requirements.sh

Minor fixes to install_requirement (undefined variable) + Loosen the Python requirements to 3.10.0+
* We can case out specific Python version as needed, but no need to restrict preemptively
---
Fails with 3.8
```
./install/install_requirements.sh
Using python executable: python3
Python version must be greater than 3.10.x. Detected version: 3.8
```
Works with 3.10.0

Minor typo + Update install_requirements.sh to support python 3.10 >=

---

install/requirements.txt

f6aa8f3d fix: remove dup dependency
commit f6aa8f3d65674c7e4f7553c38e9d8ef9d7e5ee13
Date:   Wed Nov 13 10:05:07 2024 +0100
fix: remove dup dependency
`gguf` was listed twice on the dependency list.

fix: remove dup dependency

---

torchchat/cli/cli.py

This fixes a bug where a user provided "fast" device arg falls through without being converted to a device. This correctly catches this case.
Bug introduced in https://github.com/pytorch/torchchat/commit/93f713f12507b5cef18a42c411030c90b9326369, 
---
Command
```
python3 torchchat.py generate llama3.1 --prompt "write me a story about a boy and his bear" --device fast
```
Original Failure:
```
RuntimeError: don't know how to restore data location of torch.storage.UntypedStorage (tagged with fast)
```

Bug Fix: Check for explicit cli device (fast)

---

torchchat/generate.py

b4153260 fix: do not print perf stat when NaN
commit b41532608d0f1648285d7794eda4331b1cfb297f
Date:   Thu Nov 14 11:04:47 2024 +0100
fix: do not print perf stat when NaN
If the chat is exited or interrupted it will still print the stats with
NaN values which is unnecessary.

fix: do not print perf stat when NaN

---

torchchat/cli/download.py

8a45be1b fix: mark model argument as mandatory
commit 8a45be1bfcd2d94b057b0ae9e40a491b376aa778
Date:   Wed Nov 13 11:02:47 2024 +0100
fix: mark model argument as mandatory
Let's gracefully fail if no model is given to the `download` command.

fix: mark model argument as mandatory

---

torchchat/generate.py

This PR is to remove tokens per sec in aggregate_metrics when jit_compile, to make the average of tokens per sec more precise. The tokens per sec is too low when jit_compile, which should not be included in aggregate_metrics.

Remove tokens per sec in aggregate_metrics when jit_compile

---

torchchat/cli/convert_hf_checkpoint.py
torchchat/cli/download.py

Closes #1360 
Replaces https://github.com/pytorch/torchchat/pull/1346
This is an updated fix for the root cause of the failure to download Mistral that was introduced in #1255

Download fix

---

torchchat/cli/builder.py

Wording of error message to include AOTI package

Clarify messages in builder.py

---

torchchat/cli/cli.py

Follow up fix for: https://github.com/pytorch/torchchat/commit/46977645de6e9e29e58fada7d600c1930ed6f67b
We want to allow "fast" to work as a manual overwrite of a `--quantize` accelerator config, which the previous PR disabled while fixing a different bug
---
No overwrite
```
python3 torchchat.py generate llama3.1 --quantize '{"precision": {"dtype":"float16"}, "executor":{"accelerator":"mps"}}'
NumExpr defaulting to 10 threads.
PyTorch version 2.6.0.dev20241002 available.
lm_eval is not installed, GPTQ may not be usable
Using device=mps
```
Overwrite with device arg
```
python3 torchchat.py generate llama3.1 --quantize '{"precision": {"dtype":"float16"}, "executor":{"accelerator":"mps"}}' --device cpu
overriding json-specified device mps with cli device cpu
NumExpr defaulting to 10 …
```

Bug fix: Enable fast to override quantize json

---

.gitignore
torchchat/edge/android/torchchat/app/build.gradle.kts

- Trivial edit to ignore the .idea directory when opening torchchat with Android Studio.
- Renamed the AAR referenced so that it's consistent with the instructions provided in the README for deploying on Android

Changing the referenced AAR so that it uses the AAR from the docs

---

docs/native-execution.md

Typo fixes in native-execution.md

Typo fixes in native-execution.md

---

docs/ADVANCED-USERS.md

* Various spelling corrections
* Remove empty performance tables
* Remove CONTRIBUTING section that is covered in the project root README

Improvements for readability in ADVANCED-USERS.md

---

docs/multimodal.md

Similar to #1384 to exercise the server , but for multimodal
1 - Run server:
1a - in background
1b - capture server_pid
2 - enable query using curl
3 - shutdown server with server pid captured in server_pid

Update multimodal.md to exercise server as part of test

---

.ci/scripts/run-docs
.github/workflows/run-readme-pr.yml

run docs/native-execution.md commands during execution

Update run-docs to include `run-docs native`

---

torchchat/utils/docs/evaluation.md

Update evaluation.md to include running tests with AOTI

Update evaluation.md to include AOTI

---

README.md

Add sleep after server startup to make sure server ready prior to client request via `curl`

Avoid curl fails due to server startup time

---

torchchat/model.py
torchchat/model_config/models.json
torchchat/model_params/Granite-3.0-2B-Instruct.json
torchchat/model_params/Granite-3.0-8B-Instruct.json
torchchat/model_params/Granite-3.1-2B-Instruct.json
torchchat/model_params/Granite-3.1-8B-Instruct.json

This PR adds support for the dense Granite models in the 3.0 and 3.1 collections
* Add granite architecture parameters
* Use granite multipliers where appropriate only if set in config
* Add `model_params` for each of the new granite models
* Add entries in `model.json` for each of the new granite models

Granite 3.0 / 3.1 dense support

---

docs/quantization.md

Resolve one instance of #1436 where we say sh but mean bash (sh is not bash on every system).

Update sh -> bash in quantization.md

---

torchchat/usages/openai_api.py

This PR fixes how the stream flag is read from a request. Sending a request like:
```
curl http://localhost:5000/v1/chat/completions   -H "Content-Type: application/json"   -d '{
"model": "llama3.1",
"stream": "False",
"max_tokens": 200,
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"content": "Hello!"
}
]
}'
```
currently results in a streaming response as a non-empty string (like 'False') is interpreted  by bool() as True.

Fix how stream flag is read from request

---

README.md
torchchat/utils/scripts/build_native.sh

@gabe-l-hart @Jack-Khuu adding to table since #1262 is complete.  Does torchchat need anything else before it's appropriate to say granite is supported?

Update README.md to include granite

---

.github/workflows/runner-cuda-dtype.yml
README.md
runner/run.cpp
torchchat/export.py

Removes the need for the `-l` in the cmake call by storing the tokenizer type during export time in the PT2.
Stacked on top of https://github.com/pytorch/torchchat/pull/896

[aoti] Remove need for -l in cmake call

---

torchchat/model.py

Picking up BC-breaking change from https://github.com/pytorch/executorch/pull/6996 that was pulled in https://github.com/pytorch/torchchat/pull/1459
https://github.com/pytorch/torchchat/pull/1459 missed a callsite resulting in test failures found in https://github.com/pytorch/torchchat/issues/1463

Update import of sdpa_with_kv_cache to custom_ops

---

torchchat/generate.py

`attention_backend` is a SDPBackend, not a string
Fixing typo from https://github.com/pytorch/torchchat/pull/1456
cc: @yanbing-j

Typo: Fix generate signature type hint for attention_backend

---

.github/workflows/run-readme-pr-linuxaarch64.yml

https://github.com/pytorch/torchchat/pull/1350 used `linux-aarch64` as the runner when we should be using `linux.arm64.2xlarge` for aarch64 instead

Update run-readme-pr-linuxaarch64.yml to use correct runner

---

torchchat/utils/scripts/install_utils.sh

ExecuTorch now has XNN pybinding built by default https://github.com/pytorch/executorch/pull/7473
Previously it was not built by default

Explicitly turning off pybindings for ExecuTorch install unless requested

---

install/install_requirements.sh
torchchat/model.py

In this PR we replace torchchat's own [RMSNorm](https://github.com/pytorch/torchchat/blob/f4ae60fc936328c7ebd4551019733dc0942c42f9/torchchat/model.py#L931-L942) implementation by nn.RMSNorm, and we bump the PyTorch pin to capture the massive speed up (30x-40x) to RMSNorm on MPS backend introduced in https://github.com/pytorch/pytorch/pull/145301
Preliminary benchmarks on an M1 Pro with 16GB RAM, show a 33% speed up on token generation when running Llama 3.2 1B with 4-bit quantization
Motivation: Token generation on MPS backend is currently CPU bound, because of MPSGraph overhead. Surprisingly, the ops that are impacting performance the most are simple ones: mul, copy_, add, where, mean, rsqrt, sub, cat, stack. Experiments on an M1 Pro show that each of those op calls on the MPS backend, …

Replace RMSNorm by nn.RMSNorm

---

install/requirements.txt

https://github.com/pytorch/torchchat/issues/1472

Update numpy requirements to no longer upper bound on 2.0

---

.ci/scripts/run-docs
.github/workflows/run-readme-pr.yml

Need to ensure this is the right runner, @lessw2020 can you please have a look -- torchchat uses the same runners as pytorch.

Add distributed tests to run-readme-pr.yml

---

README.md
tokenizer/hf_tokenizer.py
torchchat/model_config/models.json
torchchat/model_params/DeepSeek-R1-Distill-Llama-8B.json

Adding Configs for https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Llama-8B
Examples:
```
python torchchat.py generate deepseek-r1:8b --compile --prompt "If x+7=9, solve for x" 
```
```
python3 torchchat.py export deepseek-r1:8b --output-aoti-package-path r1.pt2
python3 torchchat.py generate deepseek-r1:8b--aoti-package-path r1.pt2 --prompt "If x+7=9, solve for x"
```

Add DeepSeek R1 Distill 8B

---

.github/workflows/more-tests.yml
torchchat/export.py

FLASH worked for dso models, so try this with methodical tests

Enable sdpa backends for server export in export.py

---

torchchat/generate.py

Seems like we should yield the `cur_token`/`next_token` when it's an eos or eot so that it is included in the `generator_func` in `chat`. Also this way `start_pos` is incremented to an empty position in the cache. Repro similar to #1462, although there is no visible response degradation. 
I've pushed logs from my trace (https://github.com/nlpfollower/torchchat/pull/2). You can see how without this yield the first id in the `input_pos` at the beginning of a round overlaps, and overwrites, the last cache entry made in the previous turn.

Decode_n_tokens yield eos/eot token

---

.github/workflows/pull.yml

test snapshot saving and loading

Update pull.yml to test snapshot saving and loading

---

.github/workflows/pull.yml

* Temporarily disabling test using `torchchat/quant_config/mobile-32.json` to unblock CI
* Updated the bitwidth of `Emb 4bit` test case to properly use 4bit instead of 8
See https://github.com/pytorch/torchchat/pull/1486 for context

Update test-tinystories-executorch: Disable config mobile-32, fix typo

---

torchchat/utils/quantize.py

https://github.com/pytorch/torchchat/issues/1506
Please refer it for more context information.
Case:
Failed to export the embedding 4bit model with the following command: python torchchat.py export stories110m --quantize torchchat/quant_config/mobile.json --output-pte-path stories110me4.pte
Solution:
Add the min, max to embedding 4bit.
Test:
The 4bit,8bit of embedding are exported successfully by the commands: Change torchchat/quant_config/mobile.json to:
{
"embedding": {"bitwidth": 8, "groupsize" : 32},
"linear:a8w4dq": {"groupsize" : 256}
}
python torchchat.py export stories110m --quantize torchchat/quant_config/mobile.json --output-pte-path stories110me8.pte
{
"embedding": {"bitwidth": 4, "groupsize" : 32},
"linear:a8w4dq": {"groupsize" : 256}
}
python torchchat.py export stories110m …

Issue:1506 Add the min, max to embedding 4bit.

---

torchchat/utils/scripts/install_et.sh
torchchat/utils/scripts/install_utils.sh

Fix bash script, this prevents us from passing `false` to `ENABLE_ET_PYBIND`.
Example cmd:
`./torchchat/utils/scripts/install_et.sh false`

Fix install ET without pybind

---

install/install_requirements.sh

Note this is the first pin in torch = 2.8+

Bump PT/Vision/Tune Pin to 25250327

---

install/requirements.txt

Release on March 27th: https://pypi.org/project/cmake/4.0.0/

Restrict CMake < 4.0.0: BC breaking version release

---

torchchat/cli/cli.py
torchchat/generate.py

This enables compile on MPS, modifying the warning message to say this is experimental and is not ready for broad use yet
We also adjust inductor's config to avoid the inductor's decomposition of mm if running on MPS backend
```
python3 torchchat.py generate stories15M --dtype float16 --prompt "Once upon a time" --num-samples 3 --device mps --compile
```

Enable compile on MPS with experimental warning

---

install/requirements.txt
pytest.ini
torchchat/model_config/tests/test_model_config.py

Add pytest to install requirements and an example test based on model_config
* Instructions and CI integration will be in following PRs
`pytest -m model_config`

Add Initial unit test example: Model_Config

---

install/install_requirements.sh
install/install_torch.sh
pyproject.toml

This is the first step towards pip-installing of torchchat. Specifically this PR:
* Adds a pyproject.toml based on `requirements.txt`
* Pulls `torch` installation instructions from `install_requirements.sh` into `install_torch.sh`
* `torch` installation will be done separately from pip install
Note that install instructions have not changed pending refactoring the [following](https://github.com/pytorch/torchchat/pull/1528) from `install_requirements.sh`
```
(
set -x
$PIP_EXECUTABLE install evaluate=="0.4.3" lm-eval=="0.4.7" psutil=="6.0.0"
)
```
---
Testing:
```
./install/install_requirements.sh; pip freeze > original.txt
./install/install_requirements.sh; pip freeze > new.txt
> diff original.txt new.txt 
None
```

[PyProject] Spin up an initial pyproject.toml allowing for local pip install

---

install/install_requirements.sh

These imports were introduced to work around an old import bug, but is no longer required; they get picked up either directly or indirectly from requirements.txt

Removing redundant installs from install_requirements.sh

---

install/install_torch.sh

PR [#150661](https://github.com/pytorch/pytorch/pull/150661) fixed issue [#150629](https://github.com/pytorch/pytorch/issues/150629). We need to bump the torch pin by one day, since [#150661](https://github.com/pytorch/pytorch/pull/150661) was included in the April 18th nightly.

mps compile: Bump PT pin to April 18th

---

torchchat/generate.py

This message is being concatenated to the generated text. Moving down to the statistics section.

move just-in-time compilation time message

---

torchchat/cli/cli.py
torchchat/generate.py

We accumulate tokens in generate mode before calling callback on them.
This avoids synchronizing GPU and CPU on each token, improving performance on MPS backend.

Accumulate tokens in generate mode

---

torchchat/cli/builder.py
torchchat/generate.py
torchchat/model.py
torchchat/usages/openai_api.py

`torchtune` now can be an optional dependency. In most of the cases, the import was just moved to a specific function or class. In the case of the `openai_api.py`, the better solution was to just remove the unused import and `Message` type hint, because it is not a real reason to have an import of an optional library in the class.

Move imports to prepare for making torchtune an optional dependency

---

torchchat/generate.py
torchchat/model.py

Follow up patch from https://github.com/pytorch/torchchat/pull/1539 which was meant to make torchtune an optional import
---
Tested with:
Success only when torchtune installed
```
python torchchat.py generate llama3.2-11B --prompt "What's in this image?" --image-prompt assets/dog.jpg --num-samples 3
```
Success regardless of torchtune install
```
python3 torchchat.py generate llama3.1-base --prompt "Once upon a time,"
```

Push torchtune install deeper in generate._gen_model_input and undo import order change for etmodel

---

README.md
torchchat/usages/eval.py

This PR replaces all instances of `pytorch-labs` with `meta-pytorch` in this repository now that the `pytorch-labs` org has been renamed to `meta-pytorch`
- Replaced all occurrences of `pytorch-labs` with `meta-pytorch`
- Only modified files with extensions: .py, .md, .sh, .rst, .cpp, .h, .txt, .yml
- Skipped binary files and files larger than 1MB due to GitHub api payload limits in the script to cover all repos in this org. Will do a more manual second pass later to cover any larger files
This PR updates files that contained the target text.
Generated by automated script on 2025-08-12T20:58:02.375454+00:00Z

[EZ] Replace `pytorch-labs` with `meta-pytorch`
